name = "veyra"
main = "src/index.js"
compatibility_date = "2024-09-01"

[assets]
directory = "."

[[d1_databases]]
binding = "DB"
database_name = "veyra"
database_id = "0f431065-816e-41e4-b428-43d59ac1a090"
